scrip = "NIFTY"

[[buy]]
strike = 18300
expiry = "20210930"
opt = "CE"
qty = 50

[[buy]]
strike = 16700
expiry = "20210930"
opt = "PE"
qty = 50

[[sell]]
strike = 18000
expiry = "20210930"
opt = "CE"
qty = 50

[[sell]]
strike = 17000
expiry = "20210930"
opt = "PE"
qty = 50
