scrip = 'BANKNIFTY'
#scrip = 'NIFTY'
#scrip = 'FINNIFTY'
#expiry = '20230608'

[exit]
strikes = '44200-0'
hedge_gap = 500

[entry]
strikes = '0-0'
hedge_gap = 500

[clients.ramesh]
exit_qty = 675
entry_qty = 675

[clients.meenakshi]
exit_qty = 550
entry_qty = 550

[clients.ashwin]
exit_qty = 400
entry_qty = 400
